// ステンドアロン HTML (coldclear2-standalone.html) から Cold Clear 2 の
// WASM 本体と wasm-bindgen グルーを取り出し、Cloudflare Worker 用の
// ESモジュール (src/cc2-glue.js) と precompiled WASM (src/cc2.wasm) を生成する。
//
// Cloudflare Workers では eval / new Function / WebAssembly.compile(bytes) が
// 禁止されているため、下記の変換を行う:
//   1. wasm は wrangler が「WebAssembly.Module の事前コンパイル済みモジュール」として
//      import できるよう src/cc2.wasm として分離する
//   2. グルーの起動は wasm_bindgen(cc2Module) に変更 (bytes から生成しない)
//   3. self.postMessage は Worker 内で使えないため __emit(...) に置き換え
//      (探索結果を cc2Messages 配列へ収集する)
"use strict";
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..', '..');
const htmlPath = path.join(root, 'coldclear2-standalone.html');
const outDir = path.join(__dirname, '..', 'src');

function fail(msg) {
  console.error('[extract-glue] ' + msg);
  process.exit(1);
}

const html = fs.readFileSync(htmlPath, 'utf8');
const m = html.match(/<script type="text\/plain" id="botWorkerSrc">([\s\S]*?)<\/script>/);
if (!m) fail('botWorkerSrc script not found in ' + htmlPath);
let glue = m[1].replace(/^\n/, '');

// ---- WASM を分離 ----
const wasmMatch = glue.match(/const bin = atob\("([^"]*)"\)/);
if (!wasmMatch) fail('wasm base64 not found in glue');
const wasmBytes = Buffer.from(wasmMatch[1], 'base64');
if (wasmBytes.length < 10000) fail('wasm looks too small (' + wasmBytes.length + ' bytes)');
fs.mkdirSync(outDir, { recursive: true });
const wasmOut = path.join(outDir, 'cc2.wasm');
fs.writeFileSync(wasmOut, wasmBytes);
console.log('[extract-glue] wrote ' + wasmOut + ' (' + wasmBytes.length + ' bytes)');

// ---- グルー変換 ----
// 1) wasmBytes() 関数を除去（wasm は別ファイル化）
glue = glue.replace(/\nfunction wasmBytes\(\) \{\n  const bin = atob\("[^"]*"\);\n[\s\S]*?\n\}\n/, '\n');
if (glue.includes('function wasmBytes()')) fail('wasmBytes() block removal failed');

// 2) Worker 内では postMessage をそのまま使えない → __emit(...) で収集
glue = glue.split('self.postMessage(').join('__emit(');

// 3) 起動は事前コンパイル済みモジュールを渡す (待機用に initReady へ保持)
glue = glue.split('wasm_bindgen(wasmBytes())').join('const initReady = wasm_bindgen(cc2Module)');
if (glue.includes('wasmBytes()')) fail('still contains wasmBytes() call');

const header = `// GENERATED by scripts/extract-glue.js — DO NOT EDIT DIRECTLY
import cc2Module from "./cc2.wasm";

const cc2Messages = [];

function __emit(msg) {
  cc2Messages.push(msg);
}

`;

const footer = `
export const cc2Engine = {
  ready: initReady,
  isReady: () => !!service,
  send: (msg) => {
    if (service) service.send_input(JSON.stringify(msg));
    else pending.push(msg);
  },
  takeSuggestion: () => {
    const i = cc2Messages.findIndex(m => m && m.type === "suggestion");
    if (i < 0) return null;
    return cc2Messages.splice(i, 1)[0];
  },
};

export default cc2Engine;
`;

const out = header + glue + footer;
const glueOut = path.join(outDir, 'cc2-glue.js');
fs.writeFileSync(glueOut, out);
console.log('[extract-glue] wrote ' + glueOut + ' (' + out.length + ' bytes)');